### ISSUE TITLE
[Bug] 메모 writer 페이지에서 사이드바에 있는 새 메모를 누르면 메모의 상세 편집으로 넘어가서 새 메모를 생성할 수 없음

### ISSUE THREAD

**Issue by memocodee** [memocode-dev/memocode_front#111]
### ✨ 버그 설명
---
사이드바의 새 메모를 누르게 되면 현재에 해당하는 메모의 상세정보를 편집할 수 있는 모달이 뜹니다.
그리고 /w 경로에서 새 메모 버튼을 누르고 저장을 누르면 새 메모가 생성되는 것이 아닌 `관리자에게 문의하세요`라는 알림이 발생합니다.

<img width="1533" alt="스크린샷 2024-05-07 오후 12 19 34" src="https://github.com/memocode-dev/memocode_front/assets/149222112/ce8d514a-1da3-416d-b9f9-a7c7ed57732e">
<img width="1499" alt="스크린샷 2024-05-07 오후 12 23 44" src="https://github.com/memocode-dev/memocode_front/assets/149222112/719b363b-bd29-45b9-b670-6f8503a85a5f">

**Comment by miruy** [comment]
해당 버그 해결했습니다.
